# Generated by Django 3.1.6 on 2021-03-04 14:08

from django.db import migrations, models
import flowcode.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=flowcode.models.user_directory_path)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
