# Generated by Django 3.1.6 on 2021-03-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowcode', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='PyFile',
        ),
    ]
