# Generated by Django 3.1.6 on 2021-03-05 06:17

from django.db import migrations, models
import flowcode.models
import flowcode.storage


class Migration(migrations.Migration):

    dependencies = [
        ('flowcode', '0002_auto_20210304_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyfile',
            name='file',
            field=models.FileField(storage=flowcode.storage.OverwriteStorage(), upload_to=flowcode.models.user_directory_path),
        ),
    ]
