# Generated by Django 3.1.6 on 2021-03-22 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flowcode', '0004_vizquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=255)),
                ('start', models.DateField()),
                ('end', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
