# Generated by Django 3.1.6 on 2021-03-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowcode', '0006_auto_20210323_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyfile',
            name='color',
            field=models.CharField(default='#fff000', max_length=6),
        ),
    ]
