# Generated by Django 3.1.6 on 2021-03-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowcode', '0007_pyfile_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyfile',
            name='color',
            field=models.CharField(default='#fff000', max_length=7),
        ),
    ]
